### ISSUE TITLE
User can create accounts

### ISSUE THREAD

**Issue by LeszczyTom** [LeszczyTom/ceri-m1-ecommerce-2022#14]
Users should be able to create accounts.
Single Sign-On google ?

**Comment by MohamedEHJ** [comment]
Backend done in https://github.com/LeszczyTom/ceri-m1-ecommerce-2022/commit/46f089e7ef666ee9f3bfb045e1f6cbd3a8db83c4 

Still need to implement Google Single Sign-On

**Comment by MohamedEHJ** [comment]
Merged in main in https://github.com/LeszczyTom/ceri-m1-ecommerce-2022/commit/69cad6dca06eaee9b4e111499072e1f6aab74b1e
